### ISSUE TITLE
How does it check if Tuna is enabled

### ISSUE THREAD

**Issue by SushiKishi** [ZyphenVisuals/zyphens-now-playing#2]
I'm having a generic "it just stopped working" error and rather than have you chase it down, I'm wondering if you could tell me how it knows when to start displaying music information and when to stop?

I've reinstalled Tuna and OBS and made a whole new folder for the ZyphenVisuals files too, nothin' doing.  Tuna is updating the files, but Song.html just isn't doing anything with them. I really did have it working right up until it just didn't, and now I can't get it to show anything anymore. I think the issue is something with Tuna, because all I can get Song.html to do is flash white, then just go transparent -- like it would if I turned Tuna off or closed the window I had it tied to.

Alternately, if it could just be "always on" and always reading the "local files" you have Tuna update, I'll just bypass Tuna altogether. If it would just try to display the text data I'm feeding it, that'd be fine, too, but it's not doing anything and I think it's because it thinks Tuna is turned off.

**Comment by ZyphenVisuals** [comment]
I know it's way too late to reply to this, but I'll write this here in case anyone else is interested.

I haven't touched this project in a long time, but from what I remember, the behavior described in the last paragraph is indeed what should be happening, and I'm not sure why it's not. The widget doesn't "check" for neither Snip nor Tuna to be running, it simply checks if there is data in the Snip_Track.txt file, and if there is, it displays all the appropriate information.
