### ISSUE TITLE
Followed instructions to the T, nothing is happening

### ISSUE THREAD

**Issue by evildisko** [ZyphenVisuals/zyphens-now-playing#3]
I followed the instructions to use the widget with snip. Did everything it said to do in the video. When I start playing a song, nothing happens, the space stays empty. 

Windows 10 x 64 and firefox. Browser and windows are both up to date.

**Comment by DanCodesStuff** [comment]
It's broken as of IDK when. Tuna changed to {}, so if snip no longer uses %, it's broken.

**Comment by ZyphenVisuals** [comment]
Hi! I just saw this.

In the last comment it's mentioned that Tuna updated something, however the original issue is reporting Snip not working. Do neither of them currently work?

**Comment by rhawky** [comment]
I'm unsure about Tuna as I use Snip by itself, but it's currently not working for me!

**Comment by ZyphenVisuals** [comment]
I see, thank you for the feedback!

I'll try to look into how the newer Snip versions work soon to figure it out. As far as Tuna, I'll see what I end up doing about it. Tuna was mostly just an afterthought,  but since a lot of people seem to use it, I'll try to get it working again as well.

**Comment by Nerxxy** [comment]
not sure what's happened, but i checked today and snip and the widget are now working for me, hope this is the case for u all too im on snip 8.0.1

**Comment by ZyphenVisuals** [comment]
Hi! After recently using this code again, I've tested the widget to work with both Snip and Tuna, following the instructions from the OBS forum.

I'll close this for now, but feel free to open a new issue if it's still not working!
