### ISSUE TITLE
CSS edits not reflected in OBS (running through Tuna)

### ISSUE THREAD

**Issue by jordgubbssaft** [ZyphenVisuals/zyphens-now-playing#8]
Heelo, I'm trying to modify the CSS, but nothing I do is reflected in the actual source in OBS. Doesn't matter if it's as simple as changing the colour of the text, nothing changes. I've tried both 'refresh cache' and restarting OBS entirely. I'm on 30.1.2 64 bit of OBS, Tuna is 1.9.9 64 bit, I'm on Windows 11. The source for the music is a VLC source directly through OBS (VLC Video Source).

It displays exactly as it should for the base installation, I just can't get anything I change in the CSS to actually get applied.

**Comment by ZyphenVisuals** [comment]
Hi! Just to confirm, it's `SongStyle.css` that isn't working, right?

**Comment by jordgubbssaft** [comment]
Ah, no, I was in the EditorStyle, didn't even notice. That would be my mistake, oops. Thank you for asking, made me realise I was in the wrong file. Teaches me to pay more attention.

**Comment by ZyphenVisuals** [comment]
Glad your issue was fixed!
